{
    "Modified": "2020-08-24 17:37:00",
    "Published": "2018-11-07 16:29:00",
    "access": {
        "authentication": "NONE",
        "complexity": "MEDIUM",
        "vector": "NETWORK"
    },
    "assigner": "cve@mitre.org",
    "cvss": 4.3,
    "cvss-time": "2020-08-24 17:37:00",
    "cvss-vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
    "cwe": "CWE-670",
    "id": "CVE-2018-19058",
    "impact": {
        "availability": "PARTIAL",
        "confidentiality": "NONE",
        "integrity": "NONE"
    },
    "last-modified": {
        "$date": 1598290620000
    },
    "references": [
        "https://access.redhat.com/errata/RHSA-2019:2022",
        "https://gitlab.freedesktop.org/poppler/poppler/issues/659",
        "https://lists.debian.org/debian-lts-announce/2019/03/msg00008.html",
        "https://usn.ubuntu.com/3837-1/"
    ],
    "summary": "An issue was discovered in Poppler 0.71.0. There is a reachable abort in Object.h, will lead to denial of service because EmbFile::save2 in FileSpec.cc lacks a stream check before saving an embedded file.",
    "vulnerable_configuration": [
        "cpe:2.3:a:freedesktop:poppler:0.71.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:14.04:*:*:*:lts:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:18.04:*:*:*:lts:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:18.10:*:*:*:*:*:*:*",
        "cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:*"
    ],
    "vulnerable_configuration_cpe_2_2": [],
    "vulnerable_product": [
        "cpe:2.3:a:freedesktop:poppler:0.71.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:14.04:*:*:*:lts:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:18.04:*:*:*:lts:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:18.10:*:*:*:*:*:*:*",
        "cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:*"
    ]
}